"""Add admin review tracking fields to EmployeeRequest

Revision ID: 9679ab4a622e
Revises: 28cd10a22a34
Create Date: 2026-09-19 23:19:26.133783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9679ab4a622e'
down_revision: Union[str, Sequence[str], None] = '28cd10a22a34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_requests', sa.Column('reviewed_by', sa.UUID(), nullable=True))
    op.add_column('employee_requests', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('employee_requests', sa.Column('rejection_reason', sa.String(), nullable=True))
    op.add_column('employee_requests', sa.Column('admin_note', sa.String(), nullable=True))
    op.create_foreign_key('fk_employee_requests_reviewed_by_users', 'employee_requests', 'users', ['reviewed_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_employee_requests_reviewed_by_users', 'employee_requests', type_='foreignkey')
    op.drop_column('employee_requests', 'admin_note')
    op.drop_column('employee_requests', 'rejection_reason')
    op.drop_column('employee_requests', 'reviewed_at')
    op.drop_column('employee_requests', 'reviewed_by')
    # ### end Alembic commands ###
